<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BitolaEvents.Application\BitolaEvents.Application.csproj" />
    <ProjectReference Include="..\BitolaEvents.Core\BitolaEvents.Core.csproj" />
    <ProjectReference Include="..\BitolaEvents.DataAccess\BitolaEvents.DataAccess.csproj" />
  </ItemGroup>

</Project>
